### ISSUE TITLE
Make DS Test circle available on the MKDD Wiki

### ISSUE THREAD

**Issue by Miepee** [cristian64/mkdd-extender#10]
Currently, the DS Test Circle is not uploaded and viewable on the Wiki (as of 05/01/23):
https://mkdd.miraheze.org/wiki/List_of_Retro_Tracks#Mario_Kart_DS
![grafik](https://user-images.githubusercontent.com/38186597/210832773-87b541b4-5dc1-4209-a799-4dbe52e43a03.png)

While the track was never playable without hacks, it's still technically a DS Track, and thus should go to that list to be viewable/downloadable publically.
(The track actually is surprisingly fun to drive on, since it's a way more intense Baby Park)

**Comment by cristian64** [comment]
Available in the wiki now: https://mkdd.miraheze.org/wiki/DS_Test_Circle.
