### ISSUE TITLE
Make it possible to view tracks + order from already extended iso

### ISSUE THREAD

**Issue by Miepee** [cristian64/mkdd-extender#11]
Sometimes I want to rearrange the tracks from an already extended iso, but after opening one, I neither see the tracks it currently uses, nor their orderings.
It would be nice if mkdd-extender would support this, so I don't have to keep it running if I want to change the tracks a few days later.

**Comment by cristian64** [comment]
Changing or reordering an already extended ISO is not something that the MKDD Extender will ever be able to do. It'd be too cumbersome, as there is certain data that is injected into the game's code (such as minimap values, or audio track indexes) and it's not easy to extract back.

Implementing an ISO viewer that lists the images of the available custom tracks would be more viable, but the current solution for _viewing_ ISO files is pretty good (yes, that's the Mario Kart: Double Dash!! game itself!), so I'm not sure I'd invest time on it.

The MKDD Extender could perhaps output a companion JSON file listing the content of the ISO. The JSON file could in fact be embedded in the ISO for later consumption in a potential viewer. The workaround for the user at the moment would be take a screenshot of the MKDD Extender after generating the ISO, and keep the screenshot next to the ISO, with the same name (but different extension).

One thing that I'd like to implement, though, is a shelf, which would allow users to store and retrieve different sets of tracks facilitating the recreation of past ISOs. Then, viewing the content of existing ISOs becomes less relevant, as they can be reproduced easily.

**Comment by Miepee** [comment]
> Changing or reordering an already extended ISO is not something that the MKDD Extender will ever be able to do.

Maybe the tool should be clearer on this? Cause I just tried changing an already extended iso, and the tool happily tried building it with changes and only complained a few minutes after. I assume this was because it only extracts the whole ISO and verifies the dol until after "build" has been selected. There doesn't happen to be a way to only extract the dol and checking that before attempting to extract the whole ISO? (And no clue how GCMs are handled here.) I know Dolphin-Emu supports that feature, but I couldn't find the dol there from its "filesystem" viewer


The ideas of a file (be it json, plain text or whatever) that lists the contents of the extended ISO, as well as the different presets I like though.

**Comment by cristian64** [comment]
Shelf mechanism introduced in 89a4cee66a364102df617970dccee8f6c60c5b6b.

**Comment by cristian64** [comment]
Description file introduced in 22044a1e0fa541260237a29ab6b2d5e2f0adedca.

**Comment by cristian64** [comment]
Better and earlier checks to detect modified input image in a60a012b5d79edd7b84d52ab39eff4314ae1c677 and 351664881e02f74b99ef62793eb35225bc4e430d.

**Comment by cristian64** [comment]
Besides the previous references to the commits, the first line in the **Instructions** dialog states that a _retail_ ISO image should be used:

> # Instructions
> ## 1. Input ISO file
> Select the path to the **retail** ISO file of Mario Kart: Double Dash!!. All regions are supported.
>
> ...

With this, I would consider the ticket as done. A viewer for extended ISO files would have few use cases (and would require a ton of work).

**Comment by Miepee** [comment]
Can something be done to fail sooner if a non-retail ISO is used? (If yes, should I open a new ticket for it?)
