### ISSUE TITLE
Error when closing application on Linux dev builds

### ISSUE THREAD

**Issue by Miepee** [cristian64/mkdd-extender#18]
When closing the application on a self-compiled build on Linux, I get this error message:
```
Traceback (most recent call last):
  File "/gitRepos/mkdd-extender/gui.py", line 1520, in closeEvent
    self._save_settings()
  File "gitRepos/mkdd-extender/gui.py", line 1555, in _save_settings
    f'{int(custom_tracks_table_header.sortIndicatorOrder())}'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SortOrder'

```

I do not get that error on the 0.2.0 release

**Comment by cristian64** [comment]
I guess your PySide6 installation is not version 6.2 LTS. Could you verify?

**Comment by Miepee** [comment]
Correct, it's `6.4.1`.
So I guess this should be closed due to being unsupported? Or do you want to keep it open as an issue/reminder for the case that you'll sooner or later upgrade PySide to a newer version?

**Comment by cristian64** [comment]
I think this one can be fixed already in a non-version-specific way, but I'm sure that, by the time another LTS is released, there will be other Qt things to fix in the GUI.

I'll update the check out instructions to install dependencies in a virtual environment, to ensure the correct versions are installed without altering the user's environment.

**Comment by Miepee** [comment]
To be fair, this is also my fault here. I generally don't install packages with pip, but with my package manager instead so I technically didn't even fully follow the setup instructions.

**Comment by cristian64** [comment]
> I think this one can be fixed already in a non-version-specific way, but I'm sure that, by the time another LTS is released, there will be other Qt things to fix in the GUI.

Done in bbd14b94afac655d9b0207d8a4045d95e6e3e6da.

> I'll update the check out instructions to install dependencies in a virtual environment, to ensure the correct versions are installed without altering the user's environment.

Done in 3327e787ea90ddf976d6481e8961b0e8d1e713f6.
