### ISSUE TITLE
Provide Linux releases in a zip

### ISSUE THREAD

**Issue by Miepee** [cristian64/mkdd-extender#2]
Personally I like them in a zip more, instead of being in a ".tar.bz2". Zip is more well known, and people less familiar with Linux (i.e. Steam Deck users) are more likely to find their way around that, than with a tar

**Comment by cristian64** [comment]
I'd say there is a reason why _tarballs_ are common on Linux. The ZIP format cannot retain file permissions (in particular, execution permissions), and a few other bits. Although this may not be relevant now, it could be relevant in the future if non-binary executables [that need execution permissions] were added to the bundle.

**Comment by Miepee** [comment]
Executable permissions shouldn't be set by default IMO. Most stuff on linux is usually done by package managers anyway, so anything downloaded from the web should be treated with extra caution.

**Comment by cristian64** [comment]
It's common to provide executable scripts with execution permissions, which lets the user identify those executable scripts. (Otherwise they are just scripts.)

I don't know of any desktop environment that won't show `.tar.bz2` as archives, so I can't imagine any user not realizing they are archives. Perhaps moving to something newer, such as `.tar.xz`, is even better?

**Comment by Miepee** [comment]
> Perhaps moving to something newer, such as .tar.xz, is even better?

Probably, it's at least more common than `.tar.bz2`.
My main concern is primarily to make it easier for people very new to linux (either in general, or coming from windows/macos), and tar is a format that's basically encountered only in linux. But considering that you only have ~2 linux users I don't think that it's that much of a priority anyway.

**Comment by cristian64** [comment]
The application only has (and will ever have?) a few tens of users, and I'm only aware of two users [that happen to be developers] on Linux: you and I. So, things like #4, #13, or #16 are really a stretch goal!
